### ISSUE TITLE
Exported requirements.txt does not include --extra-index-url

### ISSUE THREAD

**Issue by fredrikaverpil** [python-poetry/poetry-plugin-export#22]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: RHEL Linux 7.6, Python 3.7.4
- **Poetry version**: 1.0.9

## Issue

I _think_ I found a bug...
I have two internal repos (the second one requries credentials which I have stored in my pyproject.toml):
```
[[tool.poetry.source]]
name = "internal-mirror"
url = "https://server/artifactory/api/pypi/pypi-remote/simple"
default = true

[[tool.poetry.source]]
name = "myproject"
url = "https://server/artifactory/api/pypi/myproject-pypi-local/simple"
secondary = true
```

Poetry successfully installs using both repos, nice!
But when I export to requirements.txt, I only get the --index-url and not the --extra-index-url definitions, which makes this requirements file incomplete and pip is unable to find my secondary repo:
```
$ poetry export --format requirements.txt --without-hashes --output requirements.txt
```
```
--index-url https://server/artifactory/api/pypi/pypi-remote/simple

myproject==3.1.7
```

To me, this looks like a bug. I would expect that the --extra-index-url would also appear in the exported requirements.txt file, right?

**Comment by mikegit21** [comment]
Is this problem solved? I still have the same problem

**Comment by ejd** [comment]
I believe this is due to a bug here:

https://github.com/python-poetry/poetry-plugin-export/blob/bb1264c3381b6e8e9ad44c0a42ac40e68ec329bf/src/poetry_plugin_export/exporter.py#L170

This should instead be:
```python
indexes_header += f"--index-url {url}\n"
```
(note the `+=` instead of `=`)

Explanation:

`Exporter._export_requirements_txt()` finds the index URLs for all dependencies and iterates over them in sorted order to generate the `--index-url` and `--extra-index-url` lines of export output.  In @fredrikaverpil 's case, the list of sorted indexes is:
```python
['https://server/artifactory/api/pypi/myproject-pypi-local/simple', 'https://server/artifactory/api/pypi/pypi-remote/simple']
```

The method *does* append an `--extra-index-url` to `indexes_header` for the first repository (the secondary one with credentials) via this line:
https://github.com/python-poetry/poetry-plugin-export/blob/bb1264c3381b6e8e9ad44c0a42ac40e68ec329bf/src/poetry_plugin_export/exporter.py#L181

But when the method handles the second repository, the default one, `indexes_header` gets overwritten due the problematic line I pointed out above.
