### ISSUE TITLE
poetry export doesn't include non-optional groups

### ISSUE THREAD

**Issue by jonapich** [python-poetry/poetry-plugin-export#299]
The `poetry export --help` description mentions this:

> --with=WITH            The optional dependency groups to include.

However, it must also be used to include non-optional groups.

e.g.:

Given the following example pyproject.toml: https://gist.github.com/jonapich/80b8090d610da02d5de5137ca96da253

I get the following trace:

```
> poetry export | grep tenacity
(empty)

> poetry export --with my | grep tenacity
tenacity==8.2.2 ; python_version >= "3.8" and python_version < "3.12" \
```

I'm on poetry 1.5.1 on Windows, but it was reproduced on Linux as well.

**Comment by bperkins24** [comment]
It seems like the default `poetry export` should match `poetry install` in terms of what gets exported.  Are breaking changes allowed at this point?

**Comment by radoering** [comment]
> Are breaking changes allowed at this point?

I am not aware of anything else that would require a major version bump so we would do it only for this change. Not sure if we want to do this.

Apart from that, I do not have a strong opinion on this. (If we should change it at all.) I think there are pros and cons for the current behavior:

- pro current behavior: I assume most users want to export only the main group because for development they use Poetry and do not need to export `requirements.txt` files; they need them only for production and there you normally want to install only `main` dependencies.
- contra current behavior: obviously inconsistent with other Poetry commands

@Secrus Do you have an opinion on this topic?
